version: 2
updates:
- package-ecosystem: npm
  directory: "/sites/status"
  schedule:
    interval: daily
    time: '06:00'
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/sites/www"
  schedule:
    interval: daily
    time: '06:00'
  open-pull-requests-limit: 20
